// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFileToWorkspace(arg1, arg2) {
  return window['go']['main']['App']['AddFileToWorkspace'](arg1, arg2);
}

export function BtnCompare(arg1, arg2) {
  return window['go']['main']['App']['BtnCompare'](arg1, arg2);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DeleteBOMFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteBOMFile'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetAnalysisRefreshDays() {
  return window['go']['main']['App']['GetAnalysisRefreshDays']();
}

export function GetAnalysisState() {
  return window['go']['main']['App']['GetAnalysisState']();
}

export function GetAnalyzeSaveState() {
  return window['go']['main']['App']['GetAnalyzeSaveState']();
}

export function GetApiCount() {
  return window['go']['main']['App']['GetApiCount']();
}

export function GetComponent(arg1) {
  return window['go']['main']['App']['GetComponent'](arg1);
}

export function GetComponents() {
  return window['go']['main']['App']['GetComponents']();
}

export function GetFilesInWorkspaceInfo(arg1) {
  return window['go']['main']['App']['GetFilesInWorkspaceInfo'](arg1);
}

export function GetLastComparison(arg1) {
  return window['go']['main']['App']['GetLastComparison'](arg1);
}

export function GetRecentWorkspaces() {
  return window['go']['main']['App']['GetRecentWorkspaces']();
}

export function GetSavedAPIKeys() {
  return window['go']['main']['App']['GetSavedAPIKeys']();
}

export function HeaderFiltersFileValidation(arg1) {
  return window['go']['main']['App']['HeaderFiltersFileValidation'](arg1);
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenExternalLink(arg1) {
  return window['go']['main']['App']['OpenExternalLink'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenImportFileDialog() {
  return window['go']['main']['App']['OpenImportFileDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function PriceCalculator(arg1, arg2) {
  return window['go']['main']['App']['PriceCalculator'](arg1, arg2);
}

export function RunAnalysis(arg1) {
  return window['go']['main']['App']['RunAnalysis'](arg1);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetAnalysisRefreshDays(arg1) {
  return window['go']['main']['App']['SetAnalysisRefreshDays'](arg1);
}

export function SetAnalyzeSaveState(arg1) {
  return window['go']['main']['App']['SetAnalyzeSaveState'](arg1);
}

export function SetApiPriority(arg1) {
  return window['go']['main']['App']['SetApiPriority'](arg1);
}

export function SetProductionQuantity(arg1, arg2) {
  return window['go']['main']['App']['SetProductionQuantity'](arg1, arg2);
}

export function StopAnalysis() {
  return window['go']['main']['App']['StopAnalysis']();
}

export function TestBOMulusAPIKey(arg1) {
  return window['go']['main']['App']['TestBOMulusAPIKey'](arg1);
}

export function TestDKCredentials(arg1, arg2) {
  return window['go']['main']['App']['TestDKCredentials'](arg1, arg2);
}

export function TestMouserAPIKey(arg1) {
  return window['go']['main']['App']['TestMouserAPIKey'](arg1);
}

export function UpdateBMLSDesignators(arg1) {
  return window['go']['main']['App']['UpdateBMLSDesignators'](arg1);
}

export function UpdateDesignators(arg1) {
  return window['go']['main']['App']['UpdateDesignators'](arg1);
}

export function UpdateLastComparison(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLastComparison'](arg1, arg2, arg3);
}

export function UpdateVersionTags(arg1) {
  return window['go']['main']['App']['UpdateVersionTags'](arg1);
}
