// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspaces} from '../models';
import {core} from '../models';
import {components} from '../models';

export function AddFileToWorkspace(arg1:workspaces.Workspace,arg2:core.XlsmFile):Promise<void>;

export function BtnCompare(arg1:Array<core.Component>,arg2:Array<core.Component>):Promise<void>;

export function CloseWindow():Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<void>;

export function DeleteBOMFile(arg1:workspaces.Workspace,arg2:workspaces.FileInfo):Promise<void>;

export function DeleteWorkspace(arg1:workspaces.Workspace):Promise<void>;

export function GetAnalysisRefreshDays():Promise<number>;

export function GetAnalysisState():Promise<core.AnalysisStatus>;

export function GetAnalyzeSaveState():Promise<boolean>;

export function GetApiCount():Promise<number>;

export function GetApiPriority():Promise<Array<string>>;

export function GetComponent(arg1:number):Promise<core.Component>;

export function GetComponents():Promise<Array<core.Component>>;

export function GetFilesInWorkspaceInfo(arg1:workspaces.Workspace):Promise<Array<workspaces.FileInfo>>;

export function GetLastComparison(arg1:string):Promise<workspaces.Comparison>;

export function GetProductionQuantity(arg1:string):Promise<string>;

export function GetRecentWorkspaces():Promise<Array<workspaces.Workspace>>;

export function GetSavedAPIKeys():Promise<workspaces.APIKeys>;

export function HeaderFiltersFileValidation(arg1:string):Promise<core.XlsmFile>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenExternalLink(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenImportFileDialog():Promise<void>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function PriceCalculator(arg1:string,arg2:number):Promise<components.PriceCalculationResult>;

export function RunAnalysis(arg1:string):Promise<void>;

export function SetActiveWorkspace(arg1:workspaces.Workspace):Promise<void>;

export function SetAnalysisRefreshDays(arg1:number):Promise<void>;

export function SetAnalyzeSaveState(arg1:boolean):Promise<void>;

export function SetApiPriority(arg1:Array<string>):Promise<void>;

export function SetProductionQuantity(arg1:string,arg2:string):Promise<void>;

export function StopAnalysis():Promise<void>;

export function TestBOMulusAPIKey(arg1:string):Promise<boolean>;

export function TestDKCredentials(arg1:string,arg2:string):Promise<boolean>;

export function TestMouserAPIKey(arg1:string):Promise<boolean>;

export function UpdateBMLSDesignators(arg1:string):Promise<void>;

export function UpdateDesignator(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateLastComparison(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateVersionTags(arg1:workspaces.Workspace,arg2:Array<workspaces.FileInfo>):Promise<void>;
